<?php

/**
 * @file
 * BADCamp panels module.
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function badcamp_panels_ctools_plugin_api($module, $api) {
  if ($module == 'panels' && $api == 'pipelines') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_ctools_plugin_dierctory()
 */
function badcamp_panels_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}