<?php

/**
 * @file BADCamp views.
 */

/**
 * Implements hook_views_api().
 *
 * Register View API information. This is required for your module to have
 * its include files loaded; for example, when implementing
 * hook_views_default_views().
 *
 * @return
 *   An array with the following possible keys:
 *   - api:  (required) The version of the Views API the module implements.
 *   - path: (optional) If includes are stored somewhere other than within
 *       the root module directory or a subdirectory called includes, specify
 *       its path here.
 */
function badcamp_views_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implementation of hook_views_default_views().
 */
function badcamp_views_views_default_views() {
  $views_path = drupal_get_path('module', 'badcamp_views'). '/views';
  $files = file_scan_directory($views_path, '.view');

  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }

  return $views;
}

/**
 * Implements hook_views_default_views_alter().
 *
 * provides, in code, default view overrides for other views from code.
 */
function badcamp_views_views_default_views_alter(&$views) {
  $views_path = drupal_get_path('module', 'badcamp_views'). '/views';
  $files = file_scan_directory($views_path, '.view');

  foreach ($files as $filename => $file) {
    if (isset($views[$file->name])) {
      require $filename;
      $views[$file->name] = $view;
    }
  }
}