<?php

define('BADCAMP_DATE_FORMAT', 'D, M jS');

/**
 * Implements hook_block().
 * Adds a block with the current number of event signups.
 */
function badcamp_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['blimp'] = array(
      'info' => t('Attendee Count'), 
    );
    $blocks['signup_form'] = array(
      'info' => t('Signup form'), 
    );
    $blocks['add_session'] = array(
      'info' => t('BADCamp session link'), 
    );
    $blocks['add_session_two'] = array(
      'info' => t('BADCamp session link no 2'), 
    );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 'blimp':
        $block = array(
          'subject' => t('Current registered Attendees'), 
          'content' => badcamp_display_block(),
        );
        break;
      case 'signup_form':
        $block = array(
          'subject' => t('Daily Event Attendance'), 
          'content' => drupal_get_form('badcamp_signup_form'),
        );
        break;
      case 'add_session':
        $block = array(
          'subject' => '', 
          'content' => badcamp_add_session(),
        );
        break;
      case 'add_session_two':
        $block = array(
          'subject' => '', 
          'content' => badcamp_add_session(),
        );
        break;
    }
    return $block;
  }
}

/**
 * Block view callback: Determines weather to show the node add link or not.
 */
function badcamp_add_session() {
  global $user;
  if ($user->uid == 0) {
    $output = '<div class="add-session logged-out">';
    $output .= t('Please log in to submit a session of your own.');
    $output .= '</div>';
  }
  else {
    $output = '<div class="add-session logged-in">';
    if (user_access('create session content')) {
      $output .= l(t('Submit a session'), 'node/add/session');
    }
    $output .= '</div>';
  }
  return $output;
}

/**
 * Get's the signup count for a certain event, or the whole camp.
 */
function badcamp_get_signup_count($nid = NULL) {
  if ($nid != NULL) {
    $query = db_query("SELECT count(DISTINCT u.uid)  FROM {signup_log} s_l INNER JOIN {users} u ON u.uid = s_l.uid WHERE s_l.nid = %d", $nid);
  }
  else {
    $query = db_query("SELECT count(DISTINCT u.uid) FROM signup_log s_l INNER JOIN users u ON u.uid = s_l.uid;");
  }
  $count = db_result($query);

  return $count;
}

/**
 * Block view callback.
 */
function badcamp_display_block() {
  $output = '<div class="badcamp-attendee-count">' . badcamp_get_signup_count() . '</div>';
  $output .= '<div class="badcamp-attending">attending</div>';
  return $output;
}

/**
 * Hide ugly stuff on session node form.
 */
function badcamp_form_session_node_form_alter(&$form, &$form_state) {
  $form['revision_information']['#access'] = FALSE;
}

/**
 * Implements hook_form_alter().
 */
function badcamp_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register') {
    // Add message above form.
    $form['message'] = array(
      '#type' => 'markup',
      '#value' => '<div class="camp-message">' . t('Already have an account? <a href="@url">Log in</a> to sign up for 2012 events!', array('@url' => url('user/login'))) . '</div>',
      '#weight' => -11,
    );

    // Remove all the ugly help text.
    unset($form['account']['name']['#description']);
    unset($form['account']['mail']['#description']);
    unset($form['account']['pass']['#description']);
    unset($form['signup']['#description']);

    // Unset unsightly fieldset labels
    unset($form['account']['#title']);
    unset($form['signup']['#title']);
    unset($form['Personal information']['#title']);

    // Change the order of the elements.
    $form['signup']['#weight'] = -10;
    $dates = array();
    $dates_formated = array();

    // Nodes are already loaded in signup_user.
    foreach (element_children($form['signup']) as $nid) {
      if (is_numeric($nid) && !empty($form['signup'][$nid]['#title']) && ($node = node_load($nid)) && (!empty($node->field_dates[0]['value']))) {
        $date = date_format_date($node->field_dates[0]['value'], 'custom', 'm/d/y');
        $dates_formated[$date] = date_format_date($node->field_dates[0]['value'], 'custom', BADCAMP_DATE_FORMAT);
        $dates[$date][$node->nid] = $form['signup'][$nid]['#title'];
      }
    }
    if ($dates) {
      ksort($dates_formated);
      $form['signup']['#access'] = FALSE;
      $form['badcamp_signup'] = array(
        '#type' => 'fieldset',
        '#tree' => TRUE,
        //'#title' => t('Sign up for BADCamp daily events'),
        '#weight' => -10,
        '#attributes' => array(
          'id' => 'badcamp-registration-events'
        ),
      );
      foreach ($dates_formated as $date => $formated) {
        $form['badcamp_signup'][$date] = array(
          '#type' => 'radios',
          '#options' => array('' => t('None')) + $dates[$date],
          '#title' => $formated,
          // Hard coded saturday and sunday
          '#default_value' => !empty($dates[$date][3]) ? 3 : (!empty($dates[$date][490]) ? 490 : ''),
        );
        $form['#validate'][] = 'badcamp_user_register_combine_signups';
      }
    }

    // remove ugly description.
    unset($form['Personal information']['profile_volunteer']['#description']);
    unset($form['Personal information']['profile_want_job']['#description']);

    // Handle the organization field
    $form['Personal information']['profile_org']['#weight'] = 10;

    // Make a 3rd column
    $form['colthree'] = array('#type' => 'fieldset', '#weight' => 20);

    // Update volunteer and job information
    $form['colthree']['profile_volunteer'] = $form['Personal information']['profile_volunteer'];
    unset($form['Personal information']['profile_volunteer']);
    $form['colthree']['profile_want_job'] = $form['Personal information']['profile_want_job'];
    unset($form['Personal information']['profile_want_job']);

    // Put a box around submit
    $form['submit']['#prefix'] = '<div class="submit-box">';
    $form['submit']['#suffix'] = '</div>';
    $form['submit']['#value'] = 'Register for BADCamp';
    $form['submit']['#weight'] = 29;
    
    // Add opt-in
    $form['optin'] = array(
      '#type' => 'markup',
      '#weight' => 30,
      '#value' => '<div class="small">' .t('When you register for the camp you will be added to our mailing list so we can keep you informed with the latest news.') . '</div>',
    );
  }
  else if ($form_id == 'user_login_block') {
    // remove only create account link.
    $options = array('attributes' => array('title' => 'Request new password via e-mail.'));
    $form['links']['#value'] = l(t('Request new password'), 'user/password');
    
    // unset destination parameter
    $form['#action'] = 'register';
  }

  // Comment form.
  if ($form_id == 'comment_form') {
    // Shorten the comment box.
    $form['comment_filter']['comment']['#rows'] = 5;
    if (array_key_exists('submit', $form)) {
      // Change submit button text.
      $form['submit']['#value'] = t('Post');
    }
  }
  
  if ($form_id == 'user_login') {
    unset($form['name']['#description']);
    unset($form['pass']['#description']);
  }
}

/**
 * Validation form that sets the badcamp signup values to signup.
 */
function badcamp_user_register_combine_signups($form, &$form_state) {
  $signups = array();
  foreach ($form_state['values']['badcamp_signup'] as $date => $value) {
    if ($value) {
      $signups[$value] = 1;
    }
  }
  form_set_value($form['signup'], $signups, $form_state);
}


/**
 * Implements hook_signup_sign_up().
 */
function badcamp_signup_sign_up($node, $account) {
  $canceled = 0;
  $notify = arg(0) == 'node';
  if (!empty($node->field_dates[0]['value']) && $account->uid && ($date = date_format_date($node->field_dates[0]['value'], 'custom', BADCAMP_DATE_FORMAT))) {
    $result = db_query('SELECT nid, sid FROM {signup_log} WHERE uid = %d', $account->uid);
    while ($row = db_fetch_object($result)) {
      $existing_signup_node = node_load($row->nid);
      if (!empty($existing_signup_node->field_dates[0]['value']) && ($date2 = date_format_date($existing_signup_node->field_dates[0]['value'], 'custom', BADCAMP_DATE_FORMAT)) && ($date2 === $date)) {
        signup_cancel_signup($row->sid, $notify);
        $canceled++;
      }
    }
  }
  if ($canceled && $notify) {
    drupal_set_message(format_plural($canceled, 'Event canceled due to conflicting schedule', 'Events canceled due to conflicting schedule'), 'warning');
  }
}

function badcamp_signup_form() {
  global $user;
  $query = db_query(db_rewrite_sql("SELECT n.nid, s.status FROM {node} n INNER JOIN signup s on n.nid=s.nid WHERE n.status = 1"));
  while ($row = db_fetch_object($query)) {
    $nids[$row->nid] = $row->status;
  }
  // If there is at least one node, add the Signup fieldset.
  if (!empty($nids)) {
    // Each node gets a checkbox.
    $dates_formated = array();
    $dates = array();
    foreach ($nids as $nid => $status) {
      if (($node = node_load($nid)) && (!empty($node->field_dates[0]['value']))) {
        $date = date_format_date($node->field_dates[0]['value'], 'custom', 'm/d/y');
        $dates_formated[$date] = date_format_date($node->field_dates[0]['value'], 'custom', BADCAMP_DATE_FORMAT);
        $dates[$date][$node->nid] = l($node->title, 'node/' . $node->nid, array('attributes' => array('target' => '_blank')));
      }
    }
    $result = db_query('SELECT nid FROM {signup_log} WHERE uid = %d', $user->uid);
    $already_signedup_for = array();
    while ($nid = db_result($result)) {
      $already_signedup_for[] = $nid;
    }
    if ($dates) {
      $form['welcome'] = array(
        '#type' => 'markup',
        '#value' => '<p>' . t('Please select wich daily events you would like 
          to attend.  <small>(You may return to this page at any time and change your 
          choices.) The <span class="full">*</span> indicates that the event is FULL.</small>') . '</p>',
      );
      ksort($dates);
      $form['badcamp_signup'] = array(
        '#tree' => TRUE,
        '#attributes' => array(
          'id' => 'badcamp-registration-events'
        ),
      );
      foreach ($dates as $date => $options) {
        $form['badcamp_signup'][$date] = array(
          '#type' => 'radios',
          '#options' => array('' => t('None')) + $options,
          '#title' => $dates_formated[$date],
          '#default_value' => reset(array_intersect(array_keys($options), $already_signedup_for)),
        );
      }
      $form['#signedup_for'] = $already_signedup_for;
      // If any disabled nids, need to disable them.
      if (in_array(0, $nids)) {
        $form['badcamp_signup']['#nids'] = $nids;
        $form['badcamp_signup']['#after_build'][] = 'badcamp_disable_signups';
      }
    }
  }

  profile_load_profile($user);
  $fields = profile_form_profile((array)$user, $user, 'Personal information', TRUE);
  if (!empty($fields['Personal information']['profile_volunteer'])) {
    $form['profile_volunteer'] = $fields['Personal information']['profile_volunteer'];
    $form['profile_volunteer']['#weight'] = 11;
    unset($form['profile_volunteer']['#description']);
  }
  if (!empty($fields['Personal information']['profile_want_job'])) {
    $form['profile_want_job']  = $fields['Personal information']['profile_want_job'];
    $form['profile_want_job']['#weight'] = 12;
    unset($form['profile_want_job']['#description']);
  }
  $form['submit'] = array(
    '#value' => (count($already_signedup_for)) ? t('Update BADCamp Signups') : t('Signup for BADCamp'),
    '#type' => 'submit',
    '#weight' => 13,
    '#prefix' => '<div class="submit-box">',
    '#suffix' => '</div>',
  );
  
  $form['clear']['#value'] = '<div class="clear-block"></div>';
  $form['clear']['#weight'] = 14;
  
  return $form;
}

/* 
 * Disable radio button if the user is NOT currently signed up for that event
 */
function badcamp_disable_signups($element) {
  // Get the NIDs that are disabled.
  $disabled_nids = array_diff_key($element['#nids'], array_filter($element['#nids']));
  foreach (element_children($element) as $date) {
    if ($nids = array_intersect_key($disabled_nids, $element[$date])) {
      foreach (array_keys($nids) as $nid) {
        // If the user isn't currently signed up for this event, disable it.
        if ($element[$date]['#default_value'] != $nid) {
          $element[$date][$nid]['#disabled'] = TRUE;
          $element[$date][$nid]['#attributes']['disabled'] = 'disabled';
        }
        // Mark as full.
        $element[$date][$nid]['#title'] = str_replace('</a>', '<span class="full">*</span></a>', $element[$date][$nid]['#title']);
      }
    }
  }
  return $element;
}

/**
 * Submit callback that signs up users if not already.
 *
 * @see badcamp_signup_sign_up()
 *
 */
function badcamp_signup_form_submit($form, &$form_state) {
  global $user;
  foreach ($form_state['values']['badcamp_signup'] as $date => $nid) {
    if ($nid && !in_array($nid, $form['#signedup_for'])) {
      signup_sign_up_user(array('uid' => $user->uid, 'nid' => $nid));
    }
    // 
    elseif (!$nid && !empty($form['badcamp_signup'][$date]['#default_value'])) {
      if ($sid = db_result(db_query('SELECT sid FROM {signup_log} WHERE uid = %d AND nid = %d', $user->uid, $form['badcamp_signup'][$date]['#default_value']))) {
        // The join takes uid and nid, the cancel takes just sid. Inconstant!
        signup_cancel_signup($sid, FALSE);
      }
    }
  }
  if ($fid = db_result(db_query('SELECT fid FROM {profile_fields} WHERE name = "profile_volunteer"'))) {
    db_query("DELETE FROM {profile_values} WHERE fid = %d AND uid = %d", $fid, $user->uid);
    db_query("INSERT INTO {profile_values} (fid, uid, value) VALUES (%d, %d, '%s')", $fid, $user->uid, $form_state['values']['profile_volunteer']);
  }
  if ($fid = db_result(db_query('SELECT fid FROM {profile_fields} WHERE name = "profile_want_job"'))) {
    db_query("DELETE FROM {profile_values} WHERE fid = %d AND uid = %d", $fid, $user->uid);
    db_query("INSERT INTO {profile_values} (fid, uid, value) VALUES (%d, %d, '%s')", $fid, $user->uid, $form_state['values']['profile_want_job']);
  }
}

